### ISSUE TITLE
UPDATE HEXR_TRANSLATOR

### ISSUE THREAD

**Issue by thatoddmailbox** [willbarkoff/stuff#1]
MOAR PHRASES
- NAO
- WHEYE
- NU
- COD
- HEXR (works for hex, nut fur hex _r_)

and plox use a better system than a zillion `.replace`s. Maybe an object?

**Comment by willbarkoff** [comment]
@thatoddmailbox Why don't you make a pull request? Also, as for the `.replace`s, do you think a hash would work?

**Comment by thatoddmailbox** [comment]
@nywillb 

> Why don't you make a pull request?

I SHALT

> Also, as for the .replaces, do you think a hash would work?

JavaScript calls them objects, but _for the most part_ they are the same as a hash in Ruby.

**Comment by thatoddmailbox** [comment]
@nywillb GO LOOK AT #2

**Comment by thatoddmailbox** [comment]
CLOSED BY MERGIFICATION OF #2
